apiVersion: v1
kind: Pod
metadata:
  labels:
    app: clair
  name: clair-scanner
spec:
  containers:
  - name: postgres
    image: docker.io/library/postgres:12
    volumeMounts:
      - mountPath: /data
        name: clair-postgres-pvc
    resources:
      requests:
        memory: "256Mi"
        cpu: "500m"
      limits:
        memory: "512Mi"
        cpu: "1"
    env:
      - name: POSTGRES_PASSWORD
        value: password
      - name: POSTGRES_USER
        value: postgres
      - name: POSTGRES_DB
        value: clair
  - name: clair
    image: quay.io/projectquay/clair:4.7.4
    command:
      - /bin/clair
      - config
      - /config/config.yml
    ports:
      - containerPort: 6060
        hostPort: 6060
      - containerPort: 6061
        hostPort: 6061
    resources:
      requests:
        memory: "128Mi"
        cpu: "250m"
      limits:
        memory: "256Mi"
        cpu: "500m"
    workingDir: /tmp
    env:
      - name: CLAIR_MODE
        value: combo
    volumeMounts:
      - mountPath: /tmp
        name: clair-tmp-pvc
      - mountPath: /config:z
        name: clair-config-pvc
  volumes:
    - name: clair-postgres-pvc
      persistentVolumeClaim:
        claimName: clair-postgres
    - name: clair-tmp-pvc
      emptyDir: {}
    - name: clair-config-pvc
      hostPath:
        path: /home/jveverka/git/podman-advanced-exercise/06_prod_images/clair_config

