FROM docker.io/library/python:3.11

WORKDIR /app
ENV COLOR=black \
    ENVIRONMENT=development

RUN pip install flask

COPY hello_app.py /app/hello_app.py

EXPOSE 8080

CMD ["python", "hello_app.py"]
