apiVersion: v1
kind: Pod
metadata:
  labels:
    app: webapp-pod
  name: webapp-pod
spec:
  containers:
  - args:
    - redis-server
    image: docker.io/library/redis:2.8
    name: redis-container
    ports:
    - containerPort: 5000
      hostPort: 5000
    volumeMounts:
    - mountPath: /data
      name: webapp-redis-pvc
  - image: localhost/flask-app:latest
    name: flask-app
  volumes:
  - name: webapp-redis-pvc
    persistentVolumeClaim:
      claimName: webapp-redis
